# action.yml
name: 'kubectl-eks-apply'
description: 'Run kubectl commands against an EKS cluster'
branding:
  icon: 'anchor'
  color: 'green'
inputs:
  kubectl-command:
    description: "The arguments to pass to kubectl."
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jonknutson/kubectl-eks-apply:v2'
  args:
    - ${{ inputs.kubectl-command }}