name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-22.04
    env:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/jonknutson
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag image
        run: |
          docker build -t $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA .
          docker tag $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA $REGISTRY/$GITHUB_REPOSITORY:latest

      - name: Push container
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run : |
          docker push $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA
          docker push $REGISTRY/$GITHUB_REPOSITORY:latest