name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-22.04
    env:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and tag images
        run: |
          docker login ghcr.io --username $GITHUB_REPOSITORY_OWNER --password $CR_TOKEN
          docker build -t $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA .
          docker tag $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA $REGISTRY/$GITHUB_REPOSITORY:latest

      - name: Add extra tags
        if: github.ref_type == 'tag'
        run: docker tag $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_REF_NAME

      - name: Push container
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run : |
          docker push $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA
          docker push $REGISTRY/$GITHUB_REPOSITORY:latest

      - name: Push extra tags
        if: github.ref_type == 'tag' && github.event_name == 'push'
        run: docker push $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_REF_NAME