name: CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    name: Tag Release
    runs-on: ubuntu-22.04
    env:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REGISTRY: ghcr.io

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/jonknutson
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Fetch and tag image
        run: |
          docker pull $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA
          docker tag $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
          docker push $REGISTRY/$GITHUB_REPOSITORY:$GITHUB_REF_NAME